services:
  pickplace:
    build: .
    container_name: pickplace
    user: "0:0"
    ports:
      - "8501:8501"
    env_file:
      - .env
    volumes:
      - ./reviews.db:/app/reviews.db 
      - ./logs:/app/logs
    shm_size: "1gb"
    restart: unless-stopped
